project:
  type: book

book:
  title: "POL232 R Handbook (W2025)"
  author: "Kenichi Ariga"
  date: "1/5/2025"
  chapters:
    - index.qmd
    - setup.qmd
    - basic.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3  
  pdf:
    documentclass: scrreprt

website:
  sidebar:
    toc: true
    toc-depth: 2

editor: visual

